all: check_types unittest localtest

check_types:
	mypy --disallow-untyped-defs --strict aah_test.py
	mypy --disallow-untyped-defs --strict aah.py
	@echo "Static type check done."

unittest:
	pytest ahh.py
	pytest ahh_test.py
	@echo "Unittest done."

localtest:
	cat data/1.in | python aah.py | diff - data/1.ans
	cat data/1.in | python aah_test.py | diff - data/1.ans
	@echo "Local kattis sample data test done."
